var parks = [
    {
        "name": "Acadia",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "44.35°N 68.21°W",
        "visited": false,
    },
    {
        "name": "American Samoa",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "14.25°S 170.68°W",
        "visited": false,
    },
    {
        "name": "Arches",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "38.68°N 109.57°W",
        "visited": false,
    },
    {
        "name": "Badlands",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "43.75°N 102.50°W",
        "visited": false,
    },
    {
        "name": "Big Bend",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "29.25°N 103.25°W",
        "visited": false,
    },
    {
        "name": "Biscayne",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "25.65°N 80.08°W",
        "visited": false,
    },
    {
        "name": "Black Canyon of the Gunnison",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "38.57°N 107.72°W",
        "visited": false,
    },
    {
        "name": "Bryce Canyon",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "37.57°N 112.18°W",
        "visited": false,
    },
    {
        "name": "Canyonlands",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "38.2°N 109.93°W",
        "visited": false,
    },
    {
        "name": "Capitol Reef",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "38.20°N 111.17°W",
        "visited": false,
    },
    {
        "name": "Carlsbad Caverns",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "32.17°N 104.44°W",
        "visited": false,
    },
    {
        "name": "Channel Islands",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "34.01°N 119.42°W",
        "visited": false,
    },
    {
        "name": "Congaree",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "33.78°N 80.78°W",
        "visited": false,
    },
    {
        "name": "Crater Lake",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "42.94°N 122.1°W",
        "visited": false,
    },
    {
        "name": "Cuyahoga Valley",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "41.24°N 81.55°W",
        "visited": false,
    },
    {
        "name": "Death Valley",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "36.24°N 116.82°W",
        "visited": false,
    },
    {
        "name": "Denali",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "63.33°N 150.50°W",
        "visited": false,
    },
    {
        "name": "Dry Tortugas",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "24.63°N 82.87°W",
        "visited": false,
    },
    {
        "name": "Everglades",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "25.32°N 80.93°W",
        "visited": false,
    },
    {
        "name": "Gates of the Arctic",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "67.78°N 153.30°W",
        "visited": false,
    },
    {
        "name": "Gateway Arch",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "38.63°N 90.19°W",
        "visited": false,
    },
    {
        "name": "Glacier",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "48.80°N 114.00°W",
        "visited": false,
    },
    {
        "name": "Glacier Bay",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "58.50°N 137.00°W",
        "visited": false,
    },
    {
        "name": "Grand Canyon",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "36.06°N 112.14°W",
        "visited": false,
    },
    {
        "name": "Grand Teton",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "43.73°N 110.80°W",
        "visited": false,
    },
    {
        "name": "Great Basin",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "38.98°N 114.30°W",
        "visited": false,
    },
    {
        "name": "Great Sand Dunes",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "37.73°N 105.51°W",
        "visited": false,
    },
    {
        "name": "Great Smoky Mountains",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "35.68°N 83.53°W",
        "visited": false,
    },
    {
        "name": "Guadalupe Mountains",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "31.92°N 104.87°W",
        "visited": false,
    },
    {
        "name": "Haleakalā",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "20.72°N 156.17°W",
        "visited": false,
    },
    {
        "name": "Hawaiʻi Volcanoes",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "19.38°N 155.20°W",
        "visited": false,
    },
    {
        "name": "Hot Springs",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "34.51°N 93.05°W",
        "visited": false,
    },
    {
        "name": "Indiana Dunes",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "41.6533°N 87.0524°W",
        "visited": false,
    },
    {
        "name": "Isle Royale",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "48.10°N 88.55°W",
        "visited": false,
    },
    {
        "name": "Joshua Tree",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "33.79°N 115.90°W",
        "visited": false,
    },
    {
        "name": "Katmai",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "58.50°N 155.00°W",
        "visited": false,
    },
    {
        "name": "Kenai Fjords",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "59.92°N 149.65°W",
        "visited": false,
    },
    {
        "name": "Kings Canyon",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "36.80°N 118.55°W",
        "visited": false,
    },
    {
        "name": "Kobuk Valley",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "67.55°N 159.28°W",
        "visited": false,
    },
    {
        "name": "Lake Clark",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "60.97°N 153.42°W",
        "visited": false,
    },
    {
        "name": "Lassen Volcanic",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "40.49°N 121.51°W",
        "visited": false,
    },
    {
        "name": "Mammoth Cave",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "37.18°N 86.10°W",
        "visited": false,
    },
    {
        "name": "Mesa Verde",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "37.18°N 108.49°W",
        "visited": false,
    },
    {
        "name": "Mount Rainier",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "46.85°N 121.75°W",
        "visited": false,
    },
    {
        "name": "New River Gorge",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "38.07°N 81.08°W",
        "visited": false,
    },
    {
        "name": "North Cascades",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "48.70°N 121.20°W",
        "visited": false,
    },
    {
        "name": "Olympic",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "47.97°N 123.50°W",
        "visited": false,
    },
    {
        "name": "Petrified Forest",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "35.07°N 109.78°W",
        "visited": false,
    },
    {
        "name": "Pinnacles",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "36.48°N 121.16°W",
        "visited": false,
    },
    {
        "name": "Redwood",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "41.30°N 124.00°W",
        "visited": false,
    },
    {
        "name": "Rocky Mountain",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "40.40°N 105.58°W",
        "visited": false,
    },
    {
        "name": "Saguaro",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "32.25°N 110.50°W",
        "visited": false,
    },
    {
        "name": "Sequoia",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "36.43°N 118.68°W",
        "visited": false,
    },
    {
        "name": "Shenandoah",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "38.53°N 78.35°W",
        "visited": false,
    },
    {
        "name": "Theodore Roosevelt",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "46.97°N 103.45°W",
        "visited": false,
    },
    {
        "name": "Virgin Islands",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "18.33°N 64.73°W",
        "visited": false,
    },
    {
        "name": "Voyageurs",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "48.50°N 92.88°W",
        "visited": false,
    },
    {
        "name": "White Sands",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "32.78°N 106.17°W",
        "visited": false,
    },
    {
        "name": "Wind Cave",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "43.57°N 103.48°W",
        "visited": false,
    },
    {
        "name": "Wrangell–St. Elias",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "61.00°N 142.00°W",
        "visited": false,
    },
    {
        "name": "Yellowstone",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "44.60°N 110.50°W",
        "visited": false,
    },
    {
        "name": "Yosemite",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "37.83°N 119.50°W",
        "visited": false,
    },
    {
        "name": "Zion",
        "url": "./public/crater-lake-national-park_250x.jpg",
        "coordinates": "37.30°N 113.05°W",
        "visited": false,
    }
]

exports.parks = parks;